spring.application.name=support

spring.datasource.url=jdbc:postgresql://localhost:5433/support
spring.datasource.username=support
spring.datasource.password=support

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true